---
- hosts: localhost
  vars: 
    state: present
    s3_bucket: tf.state.bucket
    region: us-east-1
    key: terraform.tfstate
    app_env: dev
  tasks:
    - name: Run Terraform Scripts
      terraform:
        project_path: "./"
        state: "{{ state }}"
        force_init: true
        backend_config:
          region: "{{ region }}"
          bucket: "{{ s3_bucket }}"
          key: "{{ key }}"
        variables_file: "{{ app_env }}.tfvars" 
        workspace: "{{ app_env }}"